Repository transcendence-inc/ft_transcendence, pull requests merged in 2025-01, with the labels that each got.

#81 public user profiles
  backend/blog/urls.py
  backend/game/models.py
  backend/game/templates/game/game_details.html
  backend/game/templates/game/player_details.html
  backend/game/templates/game/players.html
  backend/game/views.py
  backend/transcendence/urls.py
  backend/users/static/users/styles.css
  backend/users/templates/users/public_profile.html
  backend/users/views.py
Labels: enhancement, dependency

#92 Cleanup: player and urlpatterns
  backend/blog/urls.py
  backend/blog/views.py
  backend/chat/views.py
  backend/game/admin.py
  backend/game/api_views.py
  backend/game/consumers.py
  backend/game/migrations/0001_initial.py
  backend/game/models.py
  backend/game/templates/game/dashboard.html
  backend/game/templates/game/game_details.html
  backend/game/urls.py
  backend/game/views.py
  backend/templates/navbar.html
  backend/transcendence/settings.py
  backend/transcendence/urls.py
  backend/users/migrations/0001_initial.py
  backend/users/migrations/0002_profile_player_friends.py
  backend/users/models.py
  backend/users/templates/users/account.html
  backend/users/templates/users/list.html
  backend/users/templates/users/login.html
  backend/users/templates/users/logout.html
  backend/users/templates/users/public_profile.html
  backend/users/templates/users/register.html
  backend/users/urls.py
  backend/users/views.py
Labels: housekeeping

#99 feat/quiz_game
  backend/blog/migrations/0001_initial.py
  backend/chat/migrations/0001_initial.py
  backend/game/migrations/0001_initial.py
  backend/game/migrations/0002_initial.py
  backend/image_app/views.py.save
  backend/quiz/__init__.py
  backend/quiz/admin.py
  backend/quiz/apps.py
  backend/quiz/consumers.py
  backend/quiz/game_logic.py
  backend/quiz/migrations/0001_initial.py
  backend/quiz/migrations/__init__.py
  backend/quiz/models.py
  backend/quiz/routing.py
  backend/quiz/static/quiz/css/quiz_game.css
  backend/quiz/static/quiz/css/room_display.css
  backend/quiz/static/quiz/css/room_list.css
  backend/quiz/static/quiz/js/quiz_logic.js
  backend/quiz/static/quiz/js/room_display.js
  backend/quiz/static/quiz/js/room_list.js
  backend/quiz/static/quiz/js/router.js
  backend/quiz/templates/quiz/index.html
  backend/quiz/tests.py
  backend/quiz/trivia.py
  backend/quiz/urls.py
  backend/quiz/views.py
  backend/requirements.txt
  backend/templates/navbar.html
  backend/transcendence/asgi.py
  backend/transcendence/settings.py
  backend/transcendence/urls.py
  backend/users/migrations/0001_initial.py
Labels: enhancement, models-updates

#102 Feat/single page
  backend/image_app/__init__.py
  backend/image_app/admin.py
  backend/image_app/apps.py
  backend/image_app/migrations/__init__.py
  backend/image_app/models.py
  backend/image_app/static/image_app/delorean-car-time-machine-night-smoke-digital-art-4k-wallpaper-uhdpaper.com-82@2@b.jpg
  backend/image_app/templates/image_app/image.html
  backend/image_app/tests.py
  backend/image_app/urls.py
  backend/image_app/views.py
  backend/image_app/views.py.save
  backend/quiz/static/quiz/js/quiz_logic.js
  backend/quiz/static/quiz/js/room_display.js
  backend/quiz/static/quiz/js/room_list.js
  backend/quiz/static/quiz/js/router.js
  backend/quiz/templates/quiz/index.html
  backend/quiz/urls.py
  backend/quiz/views.py
  backend/static/js/navbar.js
  backend/static/js/router.js
  backend/templates/index.html
  backend/templates/navbar.html
  backend/transcendence/settings.py
  backend/transcendence/urls.py
  backend/transcendence/views.py
Labels: enhancement
